### ISSUE TITLE
style: design a Card

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#24]
Right now, [JobItem](https://github.com/madina0801/JobTrackr/blob/main/src/components/JobItem.jsx) card looks bad. I would like it to look prettier. Now I use Tailwind for styles :)

**Comment by MyBaBB** [comment]
Hi,  I can help you with if you want to give it to me.

**Comment by madina0801** [comment]
Here you go :)

**Comment by MyBaBB** [comment]
Thank you,   Do you have any special requests?

**Comment by madina0801** [comment]
Move delete button to the upper right corner and zoom up a card a little bit (or add neon light effect) on hover :) it's up to you, but feel free to reach out if you'll have any questions :)

**Comment by MyBaBB** [comment]
ok sorry ,  I just read this ,    let me get some coffee and I will put it there for you.

**Comment by MyBaBB** [comment]
ok,  Check out what I have done so far with the mirror blue/white gradient effect while  I work on the rest.

**Comment by MyBaBB** [comment]
something happen I will revert and fix.  hold tight, check back in a bit.

**Comment by MyBaBB** [comment]
ok you can review the work I did,   I started over and you can use the last two commits that I posted so that it will be clean and easy.   I did not see your previous comment about it until I pushes it .  we were talking at about the same time.   Once I fixed the tailwind issue the rest of your page corrected itself with the tailwind styles that were on there previously.   We can continue if you like,   Just message me for any thing that you need.   Or let me know if I need to adjust anything on there now. 🤠

**Comment by MyBaBB** [comment]
![Screenshot 2024-03-25 044332](https://github.com/madina0801/JobTrackr/assets/120271705/716b8ca2-52ee-44a2-8a0c-f007f83a8a3e)

**Comment by MyBaBB** [comment]
The green glow is on hover and it also gets a little bigger on hover
