### ISSUE TITLE
Logo in navbar is not displayed

### ISSUE THREAD

**Issue by madina0801** [madina0801/JobTrackr#9]
Logo in [Navbar](https://github.com/madina0801/JobTrackr/blob/main/src/components/layout/Navbar.jsx) component renders perfectly fine locally, but on the [website](https://job-trackr-00f2.onrender.com/) it's not seen. I believe we need to require/import logo.svg before using it.

**Comment by ahmed-hany94** [comment]
Hello, I think I might have a solution for this problem.
According to the [docs pertaining to deploying on render](https://vitejs.dev/guide/static-deploy#render), you perform these two steps
```
- Build Command: npm run build
- Publish Directory: dist
```

This means that code is being run from the **dist** directory which probably doesn't have the `logo.svg` and hence can't find it.

> Logo in [Navbar](https://github.com/madina0801/JobTrackr/blob/main/src/components/layout/Navbar.jsx) component renders perfectly fine locally

It works fine locally because you are running `npm run dev` which runs the website from the **top directory** where `logo.svg` is located.

Solution:
- You copy the `logo.svg` in the `dist` directory. Maybe you can add it as a script to be run before you run ` npm run build` if you have a lot of assets.
- Or you can change the import path so instead of 
```
<img class="logo" alt="J" src="./logo.svg" ... >
```
it becomes
```
<img class="logo" alt="J" src="../logo.svg" ... >
```
but this would break locally.

---

Sorry these are the solutions I can come up with. I have had a similar issue as I have used `render` for one of my projects.
Hope this helps.

**Comment by madina0801** [comment]
Thank you for you response! What worked for me was installing file-loader for webpack and importing logo to the Navbar component :)
